let owners = [
    {
        id: "1",
        username: "Owner1",
        password: "1",
        type: "owner",
        postcode: "",
        coordinates: [],
        bio: "",
        profilePicture: "",
        rating: 0,
        additionalinfo: "",
        badges: [],
        images: [],
        walkprice: '--',
        sitprice: '--',
    },
    {
        id: "2",
        username: "Owner2",
        password: "2",
        type: "owner",
        postcode: "",
        coordinates: [],
        bio: "",
        profilePicture: "",
        rating: 0,
        additionalinfo: "",
        badges: [],
        images: [],
        walkprice: '--',
        sitprice: '--',
    },
    {
        id: "3",
        username: "Owner3",
        password: "3",
        type: "owner",
        postcode: "",
        coordinates: [],
        bio: "",
        profilePicture: "",
        rating: 0,
        additionalinfo: "",
        badges: [],
        images: [],
        walkprice: '--',
        sitprice: '--',
    }
]

export {owners}